### ISSUE TITLE
Question: more repositories

### ISSUE THREAD

**Issue by mozesa** [Enforcer/clean-architecture#110]
Dear **@Enforcer**,

I would like to ask for your opinion.

I am about to (try to) implement clean architecture 2nd time 😄 so...
Currently I use `sqlite` as my permanent repository.

And now I try to find a place for an in _memory_ database-like structure which is actually a key-value store, from which I can push updates to the web gui via `websocket` based on an _on-change-event_.

I have different use-cases and each use-case result always is saved into the permanent repository but besides that I would like to save that into the _memory_ database as well.

How should I organize the code, what would be the best place where I do both the _sqlite_ and _memory_ save as well?

I would like to ask another one as well.
Where should I put the module of a `mysql` repository. I mean this repo is only responsible for backup and actually it copies just the content of the local `sqlite` repo. It has `models`, `dao`, `facade` currently, but I am a bit tentative whether I should put in `db_infrastructure` or somewhere else. 

Thanks for your help in advance.

Best Regards,
**András**

**Comment by Enforcer** [comment]
Hi, sorry for no reply - I must have misconfigured Github e-mails and I receive none. Are you still struggling?
