### ISSUE TITLE
Implementation doubts

### ISSUE THREAD

**Issue by DavidATS** [Enforcer/clean-architecture#83]
Hey, thank you for sharing this amazing project. I have been studying the code and your book to implement Domain Events in the projects I'm working on, however, I can't quite understand how the events are consumed, I have seen some other examples such as the one in cosmic python where they use a Redis pubsub listener as another entry point. Is this a similar case? If not, could you, please, explain your approach?
Thanks in advance!

**Comment by Enforcer** [comment]
Hey, I can see you closed the issue before I could see it. Is this still something I can help you with?

**Comment by Enforcer** [comment]
BTW I think you might be confusing Domain Events with messages used for integration between bounded contexts?

**Comment by DavidATS** [comment]
Hey, thanks for the reply, I was indeed confusing the concepts, I managed to solve the doubts I had thanks 😄
