### ISSUE TITLE
EPUB version of the book is not proper to EPUB standard

### ISSUE THREAD

**Issue by mozesa** [Enforcer/clean-architecture#84]
Dear **Sebastian**,

I would like to ask for your kind help in connection with the `epub` version of the book.
What I want to read your book using `Google Play Books`. The problem is that the book is not formated adequately.

![SmartSelect_20200628-083451_Samsung Internet](https://user-images.githubusercontent.com/49973426/85940178-2d17a000-b91b-11ea-8cd1-f374b726942a.jpg)

Thanks for your help in advance.

**Comment by Enforcer** [comment]
Hey, thanks for the report. At the very moment, I am preparing a reformatted version with new epub and a few slight updates. Stay tuned!

**Comment by mozesa** [comment]
Hello **Sebastian**,

I am really looking forward to reading the reformatted version of your book. 

I find the book very helpful and thorough.

Thanks for your effort!

**Comment by Enforcer** [comment]
Hello @mozesa ,
you can expect a new version by the end of this week. Sorry for the delay, but several parts required more thorough lifting and updating content.

I still want to test it against a few ebook readers & apps (Nook, iPad and `Google Play Books`) and if everything is acceptable, I will update the book on the Leanpub.

All the best :)

**Comment by mozesa** [comment]
Dear **Enforcer**,

Thanks for your feedback!
Your book has helped me a lot so far.
I really like that you show the example project as _whole_.

Thanks again! 😄

**Comment by mozesa** [comment]
Dear **@Enforcer**,

I really appreciate your help.
Now I am going to close this issue as it has been solved.

Thanks again!

All the best!
